import React from "react";
import Provider from "./provider";
import 'bootstrap/dist/css/bootstrap.css';
import TopNavbar from "../components/layout/TopNavbar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Provider>
            <TopNavbar/>
            <div className="container">
                {children}
            </div>
        </Provider>
        </body>
        </html>
    )
}